# Generated by Django 5.0.14 on 2026-02-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_order_n_1336be_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
