# Generated by Django 5.2.10 on 2026-01-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products/%Y/%m/'),
        ),
    ]
